
#!/bin/bash
# Generated cleanup script - Review before running!

# Remove empty files
rm "E:/Room Finder/room/LOGO_README.md"
rm "E:/Room Finder/room/postcss.config.js"
rm "E:/Room Finder/room/public/scroll-optimizer.js"
rm "E:/Room Finder/room/src/AboutPage.js"
rm "E:/Room Finder/room/src/background-fix.css"
rm "E:/Room Finder/room/src/ColorPaletteShowcase.css"
rm "E:/Room Finder/room/src/ColorPaletteShowcase.js"
rm "E:/Room Finder/room/src/colors.css"
rm "E:/Room Finder/room/src/components/AdvancedSearchFilter_README.md"
rm "E:/Room Finder/room/src/components/FloatingSearchBar.js"
rm "E:/Room Finder/room/src/components/HERO_SECTION_README.md"
rm "E:/Room Finder/room/src/components/index.js"
rm "E:/Room Finder/room/src/components/ModernNavbar.css"
rm "E:/Room Finder/room/src/components/ModernNavbar.js"
rm "E:/Room Finder/room/src/components/ModernNavbar_README.md"
rm "E:/Room Finder/room/src/components/MultiStepForm.js"
rm "E:/Room Finder/room/src/components/ProfileModal.js"
rm "E:/Room Finder/room/src/components/PropertyCard_README.md"
rm "E:/Room Finder/room/src/components/RevampedSearch.css"
rm "E:/Room Finder/room/src/components/RevampedSearch.js"
rm "E:/Room Finder/room/src/components/ui/index.js"
rm "E:/Room Finder/room/src/components/ui/ModernNavbar.css"
rm "E:/Room Finder/room/src/components/ui/ModernNavbar.js"
rm "E:/Room Finder/room/src/components/ui/Navbar.css"
rm "E:/Room Finder/room/src/components/ui/Navbar.js"
rm "E:/Room Finder/room/src/components/UniversalSearchBar.css"
rm "E:/Room Finder/room/src/components/UniversalSearchBar.js"
rm "E:/Room Finder/room/src/ContactPage.js"
rm "E:/Room Finder/room/src/css/home.css"
rm "E:/Room Finder/room/src/DesignSystemPage.css"
rm "E:/Room Finder/room/src/DesignSystemPage.js"
rm "E:/Room Finder/room/src/FooterDemo.css"
rm "E:/Room Finder/room/src/FooterDemo.js"
rm "E:/Room Finder/room/src/HomePage.js"
rm "E:/Room Finder/room/src/index.css"
rm "E:/Room Finder/room/src/ListingsGrid.js"
rm "E:/Room Finder/room/src/pages/ProfilePage.js"
rm "E:/Room Finder/room/src/pages/SearchPage.js"
rm "E:/Room Finder/room/src/PostRoomPage.js"
rm "E:/Room Finder/room/src/PropertyShowcase.css"
rm "E:/Room Finder/room/src/PropertyShowcase.js"
rm "E:/Room Finder/room/src/RoomCard.css"
rm "E:/Room Finder/room/src/SearchFilterShowcase.css"
rm "E:/Room Finder/room/src/SearchFilterShowcase.js"
rm "E:/Room Finder/room/src/SearchPage.js"
rm "E:/Room Finder/room/src/Testimonials.js"
rm "E:/Room Finder/room/src/TestImports.js"
rm "E:/Room Finder/room/src/UIShowcase.css"
rm "E:/Room Finder/room/src/UIShowcase.js"
rm "E:/Room Finder/room/src/utils/ultraStableBackground.js"
rm "E:/Room Finder/room/_backup/20250718_094802/src/scroll-fix-new.css"
rm "E:/Room Finder/room/_backup/20250718_094802/src/ultra-stable-background.css"

# Remove nearly empty files - REVIEW THESE FIRST
# rm "E:/Room Finder/room/src/components/Footer.js"

# Remove empty directories
rmdir "E:/Room Finder/room/src/assets/icons"
rmdir "E:/Room Finder/room/src/assets/images"
rmdir "E:/Room Finder/room/src/components/ui/feedback"
rmdir "E:/Room Finder/room/src/components/ui/inputs"
rmdir "E:/Room Finder/room/src/components/ui/navigation"
rmdir "E:/Room Finder/room/src/hooks"
rmdir "E:/Room Finder/room/src/layouts"
rmdir "E:/Room Finder/room/src/styles/components"
rmdir "E:/Room Finder/room/_backup/20250718_094851/pages_backup"
rmdir "E:/Room Finder/room/_backup/20250718_094851/styles_backup"
rmdir "E:/Room Finder/room/_backup/20250718_094954/pages_backup"
rmdir "E:/Room Finder/room/_backup/20250718_094954/styles_backup"
rmdir "E:/Room Finder/room/_backup/src"
